data:
  artifacts.oci.signer: kms
  artifacts.taskrun.signer: kms
  signers.kms.kmsref: "hashivault://frsca"
  signers.kms.auth.address: "http://vault.vault:8200"
  signers.kms.auth.oidc.path: jwt
  signers.kms.auth.oidc.role: "spire-chains-controller"
  signers.kms.auth.spire.sock: "unix:///spiffe-workload-api/spire-agent.sock"
  signers.kms.auth.spire.audience: TESTING
  spire.enabled: "true"
  spire.socketPath: "unix:///spiffe-workload-api/spire-agent.sock"