---
name: docs
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - ".github/**"
      - "docs/**"
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
      - name: build
        uses: shalzz/zola-deploy-action@379fe3f34e1ae82aaff02c9500a3cfa7a8f4d5b2  # v0.17.1
        env:
          BUILD_DIR: docs
          BUILD_ONLY: true
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@64b46b4226a4a12da2239ba3ea5aa73e3163c75b  # v3.9.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
